#index:
controllers:
    resource: '../src/Controller/'
    type:     annotation
    prefix:   /

# redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /home
        permanent: true